version: '3'
services:
  rabbit:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment: 
      - RABBITMQ_DEFAULT_USER=root #设置用户名
      - RABBITMQ_DEFAULT_PASS=123456 #设置密码
    volumes: #挂载目录
      - /home/rabbitmq/lib:/var/lib/rabbitmq 